# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - job4me

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E565B3E710048CE93A4AC65371DA982 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6BC9DE63FAA245469EB6FC016A7B1133 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F4F6047A4004C53B7E979AE9791969E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'job4me'
          slot-name: 'Production'
          package: '*.jar'
          env: |
            AZURE_DB: ${{ secrets.AZURE_DB }}
            AZURE_DB_USER: ${{ secrets.AZURE_DB_USER }}
            AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
            LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
            RECOMMENDATION_API_URL: ${{ secrets.RECOMMENDATION_API_URL }}
            RECOMMENDATION_API_KEY: ${{ secrets.RECOMMENDATION_API_KEY }}
            STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
            CV_FONT: ${{ secrets.CV_FONT }}
            STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          